

volumes:
  database:

networks:
  backend:

services:
  backend:
    build: ./backend
    container_name: backend_dictionnaire
    env_file: .env
    hostname: backend
    ports:
      - 7500:5000
    restart: always
    depends_on:
      - postgres
    networks:
      - backend
    volumes:
      - ./backend:/app

  postgres:
    image: postgres:16beta1-alpine3.18
    container_name: postgres_dictionnaire
    hostname: postgres
    env_file: .env
    restart: always
    ports:
      - 7501:5432
    volumes:
      - database:/var/lib/postgresql/data/
    networks:
      - backend

  adminer:
    image: adminer:4.8.1-standalone
    container_name: adminer_dictionnaire
    env_file: .env
    restart: always
    ports:
      - 7502:8080
    cnetworks:
      - backend
  
  # nginx:
  #   container_name: nginx_dictionnaire
  #   image: nginx:latest
  #   restart: unless-stopped
  #   env_file: .env
  #   hostname: api
  #   networks:
  #     - backend # Update this with your application service network
  #   volumes:
  #     - ./nginx/secure/:/etc/nginx/templates/
  #     - /etc/localtime:/etc/localtime:ro
  #     - ./nginx/certbot/conf:/etc/letsencrypt
  #     - ./nginx/certbot/www:/var/www/certbot
  #     - ./nginx/99-autoreload.sh:/docker-entrypoint.d/99-autoreload.sh  # Script to autoreload Nginx when certs are renewed

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./nginx/certbot/conf:/etc/letsencrypt
  #     - ./nginx/certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh - 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'" 

  frontend:
    build: ./frontend
    container_name: frontend_dictionnaire
    env_file: .env
    depends_on: 
      - backend
    ports:
      - 7503:5173
    restart: always
    networks:
      - backend
    volumes:
      - ./frontend:/app

  # swagger:
  #   image: swaggerapi/swagger-ui
  #   container_name: swagger_camagru
  #   env_file: .env
  #   ports:
  #     - 7506:8080
  #   restart: always
  #   networks:
  #     - backend

  # mail:
  #   image: marcopas/docker-mailslurp
  #   container_name: mail_cm3000

